# 1.1 python实现pca（detail）

In [13]:
import numpy as np
#10样本3特征的样本集, 行为样例，列为特征维度
#样本矩阵X
X = np.array([[10, 15, 29],
              [15, 46, 13],
              [23, 21, 30],
              [11, 9,  35],
              [42, 45, 11],
              [9,  48, 5],
              [11, 21, 14],
              [8,  5,  15],
              [11, 12, 21],
              [21, 20, 25]])
#K阶降维矩阵的K值
K = np.shape(X)[1] - 1
#矩阵X的中心化
centrX = [] 
#样本集的协方差矩阵C
C = []
#样本矩阵X的降维转换矩阵
U = [] 
#样本矩阵X的降维矩阵Z
Z = []    

'''矩阵X的中心化'''
mean = np.array([np.mean(attr) for attr in X.T])
#样本集的中心化
centrX = X - mean

'''求样本矩阵X的协方差矩阵C'''
#样本集的样例总数
ns = np.shape(centrX)[0]
#样本矩阵的协方差矩阵C
C = np.dot(centrX.T, centrX)/(ns - 1)

'''求X的降维转换矩阵U, shape=(n,k), n是X的特征维度总数，k是降维矩阵的特征维度'''
#先求X的协方差矩阵C的特征值和特征向量
#特征值赋值给a，对应特征向量赋值给b。
a,b = np.linalg.eig(C) 
#给出特征值降序的topK的索引序列
ind = np.argsort(-1*a)
#构建K阶降维的降维转换矩阵U
UT = [b[:,ind[i]] for i in range(K)]
U = np.transpose(UT)

'''按照Z=XU求降维矩阵Z, shape=(m,k), n是样本总数，k是降维矩阵中特征维度总数'''
Z = np.dot(X, U)

print('PCA法降维之后的矩矩阵如下：',Z)

PCA法降维之后的矩矩阵如下： [[ -4.56200104 -21.2336912 ]
 [-39.28629002 -15.26038349]
 [-13.30247561 -32.55597794]
 [  2.71190993 -25.49365577]
 [-47.37858268 -38.02120912]
 [-42.36990935  -6.0258027 ]
 [-16.00097294 -14.43926499]
 [ -0.822856   -13.7001301 ]
 [ -5.42741864 -18.56462272]
 [-13.80800193 -28.51385518]]


# 1.2 python实现pca（调接口）

In [14]:
#coding=utf-8

import numpy as np
from sklearn.decomposition import PCA
X = np.array([[-1,2,66,-1], [-2,6,58,-1], [-3,8,45,-2], [1,9,36,1], [2,10,62,1], [3,5,83,2]])  #导入数据，维度为4
pca = PCA(n_components=3)   #降到2维
pca.fit(X)                  #训练
newX=pca.fit_transform(X)   #降维后的数据
# PCA(copy=True, n_components=2, whiten=False)
print(pca.explained_variance_ratio_)  #输出贡献率
print(newX)                  #输出降维后的数据

[0.95713353 0.03398198 0.00872022]
[[  7.96504337   4.12166867   1.43741053]
 [ -0.43650137   2.07052079  -0.9937735 ]
 [-13.63653266   1.86686164  -1.76428642]
 [-22.28361821  -2.32219188   2.06505529]
 [  3.47849303  -3.95193502  -1.33526047]
 [ 24.91311585  -1.78492421   0.59085455]]


# 2.实现canny（调接口）

In [17]:
import cv2
import matplotlib.pyplot as plt

img = cv2.imread('gray_test.jpg')
# 原图灰度化
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# 高斯滤波 卷积 3*3
img_blur = cv2.GaussianBlur(img_gray, (3, 3), 0)
# x梯度
xgrad = cv2.Sobel(img_blur, cv2.CV_16SC1, 1, 0)
# y梯度
ygrad = cv2.Sobel(img_blur, cv2.CV_16SC1, 0, 1)
# 使用梯度参数进行边缘检测 阈值50-150
edge1 = cv2.Canny(xgrad, ygrad, 50, 150)
# 直接用高斯滤波结果进行边缘检测 阈值 50-150
edge2 = cv2.Canny(img_blur, 50, 150)
cv2.imshow('origin image', img)
cv2.imshow('origin image', edge1)
cv2.imshow('origin image', edge2)
cv2.waitKey()

-1